[package]
name = "morph"
version = "0.3.1"
edition = "2021"
license = "Apache-2.0"
description = "Morph CLI (run, fmt, test)."

[dependencies]
morphc = { path = "../morphc" }
morphrt = { path = "../morphrt" }

[dev-dependencies]
tempfile = "3.10"
