[package]
name = "enkai_native"
version = "1.3.0"
edition = "2021"

[lib]
name = "enkai_native"
crate-type = ["cdylib", "rlib"]

[dependencies]
memmap2 = "0.9"
sha2 = "0.10"
zstd = "0.13"
serde_json = "1.0"
native-tls = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }

